apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-autoscale-cluster
spec:
  selector:
    matchLabels:
      redis: redis-cluster-pods-lbl
  replicas: 6
  template:
    metadata:
      labels:
        redis: redis-cluster-pods-lbl
    spec:
      containers:
      - name: redis-cluster-pod
        image: redis-autoscale-cluster:0.1
        command: ['/bin/bash','/entrypoint.sh']
        resources:
          requests:
            memory: "8Mi"
            cpu: "150m"
          limits:
            memory: "16Mi"
            cpu: "200m"
