apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-cluster-service-lbl
  name: redis-cluster-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    redis: redis-cluster-pods-lbl
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-cluster-coordinator-service-lbl
  name: redis-cluster-coordinator-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis-cluster-coordinator-lbl
